// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValueObjectDemo.Data;

namespace ValueObjectDemo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ValueObjectDemo.Types.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ValueObjectDemo.Types.Person", b =>
                {
                    b.OwnsOne("ValueObjectDemo.Types.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("City")
                                .HasColumnType("nvarchar(150)")
                                .HasMaxLength(150)
                                .HasDefaultValue("");

                            b1.Property<string>("State")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("State")
                                .HasColumnType("nvarchar(60)")
                                .HasMaxLength(60)
                                .HasDefaultValue("");

                            b1.Property<string>("StreetAddress")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("StreetAddress")
                                .HasColumnType("nvarchar(600)")
                                .HasMaxLength(600)
                                .HasDefaultValue("");

                            b1.HasKey("PersonId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("ValueObjectDemo.Types.ZipCode", "ZipCode", b2 =>
                                {
                                    b2.Property<Guid>("AddressPersonId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Code")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnName("ZipCode")
                                        .HasColumnType("nvarchar(max)")
                                        .HasDefaultValue("");

                                    b2.Property<string>("PlusFour")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnName("PlusFour")
                                        .HasColumnType("nvarchar(max)")
                                        .HasDefaultValue("");

                                    b2.HasKey("AddressPersonId");

                                    b2.ToTable("Addresses");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressPersonId");
                                });
                        });

                    b.OwnsOne("ValueObjectDemo.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Status")
                                .HasColumnType("nvarchar(600)")
                                .HasMaxLength(600)
                                .HasDefaultValue("Available");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
